columns_rename_mapping = {' right_elbow': 'RElbow',
                          'left_ankle': 'LAnkle',
                          'left_ear': 'LEar',
                          'left_elbow': 'LElbow',
                          'left_eye': 'LEye',
                          'left_hip': 'LHip',
                          'left_knee': 'LKnee',
                          'left_shoulder': 'LShoulder',
                          'left_wrist': 'LWrist',
                          'neck': 'Neck',
                          'nose': 'Nose',
                          'right_ankle': 'RAnkle',
                          'right_ear': 'REar',
                          'right_eye': 'REye',
                          'right_hip': 'RHip',
                          'right_knee': 'RKnee',
                          'right_shoulder': 'RShoulder',
                          'right_wrist': 'RWrist'
                          }
